"use client";
import {useEffect,useMemo,useState} from "react";
import {Home,Menu,Search,RefreshCw,Link2,Shield,Swords,Sparkles,Feather,PawPrint,ExternalLink,Unlink,Database,LockKeyhole} from "lucide-react";
import styles from "./character.module.css";
import {classifyCharacterSkill} from "./character-model.mjs";
const STORAGE="daevexus.character-link.v1";
const regions=[["naw","Global · NA West"],["nae","Global · NA East"],["eu","Global · Europe"],["sa","Global · South America"],["asia","Global · Asia"],["tw","Taiwan · Lab"]];
const fmt=n=>new Intl.NumberFormat("en-US").format(Number(n)||0);
const race=id=>Number(id)===1?"Elyos":Number(id)===2?"Asmodian":"Unknown";
export default function MyCharacter(){
 const[region,setRegion]=useState("naw"),[name,setName]=useState(""),[serverId,setServerId]=useState(""),[profileUrl,setProfileUrl]=useState(""),[results,setResults]=useState([]),[linked,setLinked]=useState(null),[syncedAt,setSyncedAt]=useState(""),[tab,setTab]=useState("overview"),[view,setView]=useState("sync"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const data=JSON.parse(raw);if(data?.character){setLinked(data.character);setSyncedAt(data.syncedAt||"");setRegion(data.character.region||"naw");}}}catch{}},[]);
 const itemLevel=useMemo(()=>linked?.stats?.find(s=>String(s.type).toLowerCase()==="itemlevel")?.value||0,[linked]);
 const acquired=useMemo(()=>[...(linked?.skills||[])].filter(s=>s.acquired===true&&Number(s.level)>0).sort((a,b)=>Number(b.equipped)-Number(a.equipped)||String(a.category||"").localeCompare(String(b.category||""))||String(a.name||"").localeCompare(String(b.name||""))),[linked]);
 const skillGroups=useMemo(()=>({active:acquired.filter(s=>classifyCharacterSkill(s.category)==="active"),passive:acquired.filter(s=>classifyCharacterSkill(s.category)==="passive"),stigma:acquired.filter(s=>classifyCharacterSkill(s.category)==="stigma")}),[acquired]);
 const persist=(character,time)=>{setLinked(character);setSyncedAt(time||"");try{localStorage.setItem(STORAGE,JSON.stringify({character,syncedAt:time}));}catch{}};
 async function search(event){event?.preventDefault();setBusy(true);setMessage("");setResults([]);try{const q=new URLSearchParams({region,keyword:name.trim()});if(serverId)q.set("serverId",serverId);const res=await fetch("/api/character-search?"+q,{cache:"no-store"}),data=await res.json();if(!data.ok)throw new Error(data.error);const matches=data.results||[];if(matches.length===1){await syncRef(matches[0]);return;}setResults(matches);if(!matches.length)setMessage(`No exact character named "${name.trim()}" was found in this region${serverId?` / server ${serverId}`:""}. Check the spelling or use the official profile URL.`);else setMessage("More than one character has this exact name. Choose the correct server.");}catch(e){setMessage(e.message||"Search failed.");}finally{setBusy(false);}}
 async function syncRef(ref){setBusy(true);setMessage("");try{const q=new URLSearchParams({region:ref.region,serverId:String(ref.serverId),characterId:ref.characterId});const res=await fetch("/api/character-sync?"+q,{cache:"no-store"}),data=await res.json();if(!data.ok)throw new Error(data.error);persist(data.character,data.syncedAt);setResults([]);setTab("overview");setView("info");}catch(e){setMessage(e.message||"Sync failed.");}finally{setBusy(false);}}
 async function linkUrl(event){event?.preventDefault();setBusy(true);setMessage("");try{const res=await fetch("/api/character-sync?"+new URLSearchParams({profileUrl}),{cache:"no-store"}),data=await res.json();if(!data.ok)throw new Error(data.error);persist(data.character,data.syncedAt);setResults([]);setTab("overview");setView("info");}catch(e){setMessage(e.message||"Could not link this profile.");}finally{setBusy(false);}}
 const unlink=()=>{setLinked(null);setSyncedAt("");setTab("overview");setView("sync");setMessage("");try{localStorage.removeItem(STORAGE);}catch{}};
 return <main className={styles.page}>
   <header className={styles.top}><a href="/?menu=open" aria-label="Open DAEVEXUS menu"><Menu/></a><div><small>DAEVEXUS · CHARACTER LAB</small><h1>{view==="sync"?"Character Sync":"Character Info"}</h1></div><a href="/" aria-label="Home"><Home/></a></header>
   {view==="sync"&&linked?<section className={styles.syncGate}>
     <div className={styles.syncCard}>
       <span className={styles.syncEyebrow}>CHARACTER SYNC</span>
       <div className={styles.syncPortrait}>{linked.profile.image?<img src={linked.profile.image} alt=""/>:<Shield/>}</div>
       <h2>{linked.profile.name}</h2>
       <p>{linked.profile.className||"Class pending"} · Lv. {linked.profile.level} · {race(linked.profile.raceId)}</p>
       <div className={styles.syncMeta}><span>{regions.find(x=>x[0]===linked.region)?.[1]||linked.region}</span><span>{linked.profile.serverName||("Server "+linked.serverId)}</span></div>
       <button className={styles.syncPrimary} onClick={()=>syncRef(linked)} disabled={busy}><RefreshCw/>{busy?" Syncing character…":" Sync character"}</button>
       {message&&<p className={styles.message}>{message}</p>}
       <div className={styles.syncLast}>Last sync<br/><b>{syncedAt?new Date(syncedAt).toLocaleString():"Never"}</b></div>
       <button className={styles.syncSecondary} onClick={unlink} disabled={busy}><Unlink/> Use another character</button>
     </div>
   </section>:view==="sync"?<section className={styles.connect}>
     <div className={styles.intro}><span>PUBLIC PROFILE LINK</span><h2>Bring your Daeva into DAEVEXUS.</h2><p>Link a public AION 2 character profile and sync the information NC exposes: level, class, combat power, stats, equipped gear, skills, Pet, Wings and progression.</p><div className={styles.safe}><LockKeyhole/><p><b>No NC/PURPLE password.</b> DAEVEXUS reads only the public character information already exposed by the official character service.</p></div></div>
     <div className={styles.forms}>
       <form onSubmit={search} className={styles.box}><div className={styles.boxTitle}><Search/><div><b>Search exact character</b><small>Exact name only · no similar-name list</small></div></div><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Character name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Exact character name" minLength={2}/></label><label>Server ID <small>optional</small><input value={serverId} onChange={e=>setServerId(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="e.g. 1201"/></label><button disabled={busy||name.trim().length<2}>{busy?"Checking…":"Find exact character"}</button></form>
       <form onSubmit={linkUrl} className={styles.box}><div className={styles.boxTitle}><Link2/><div><b>Link from profile URL</b><small>Best option for our first lab test</small></div></div><label>Official character URL<textarea value={profileUrl} onChange={e=>setProfileUrl(e.target.value)} placeholder="https://aion2.plaync.com/en-us/characters/… or https://tw.ncsoft.com/aion2/characters/…"/></label><button disabled={busy||!profileUrl.trim()}>{busy?"Syncing…":"Link & sync"}</button><p className={styles.mini}>Tip: open your character on the official AION 2 Character Info page, copy the URL and paste it here.</p></form>
     </div>
     {message&&<p className={styles.message}>{message}</p>}
     {!!results.length&&<div className={styles.results}><div className={styles.resultsHead}><b>Exact-name matches</b><span>{results.length}</span></div>{results.map(r=><button key={r.serverId+":"+r.characterId} onClick={()=>syncRef(r)} disabled={busy}><span className={styles.avatar}>{r.profileImage?<img src={r.profileImage} alt=""/>:<Shield/>}</span><span><b>{r.name}</b><small>Lv. {r.level} · {r.serverName||("Server "+r.serverId)} · {race(r.race)}</small></span><strong>LINK</strong></button>)}</div>}
   </section>:linked?<section className={styles.dashboard}>
     <aside className={styles.profile}>
       <div className={styles.portrait}>{linked.profile.image?<img src={linked.profile.image} alt=""/>:<Shield/>}</div><span className={styles.region}>{regions.find(x=>x[0]===linked.region)?.[1]||linked.region}</span><h2>{linked.profile.name}</h2><p>{linked.profile.className||"Class pending"} · Lv. {linked.profile.level} · {race(linked.profile.raceId)}</p><small>{linked.profile.serverName||("Server "+linked.serverId)}{linked.profile.guildName?" · "+linked.profile.guildName:""}</small>
       <a className={styles.official} href={linked.profileUrl} target="_blank" rel="noreferrer">Official profile <ExternalLink/></a>
       <button className={styles.infoBack} onClick={()=>{setMessage("");setView("sync");}}><RefreshCw/> Back to Character Sync</button>
       <div className={styles.syncTime}>Last sync<br/><b>{syncedAt?new Date(syncedAt).toLocaleString():"—"}</b></div>
     </aside>
     <div className={styles.content}>
       <div className={styles.metrics}><article><small>COMBAT POWER</small><strong>{fmt(linked.profile.combatPower)}</strong></article><article><small>LEVEL</small><strong>{linked.profile.level||"—"}</strong></article><article><small>ITEM LEVEL</small><strong>{itemLevel?fmt(itemLevel):"—"}</strong></article><article><small>EQUIPMENT</small><strong>{linked.equipment.length}</strong></article><article><small>SKILLS</small><strong>{acquired.length}</strong></article></div>
       <nav className={styles.tabs}>{[["overview","Overview"],["equipment","Equipment"],["skills","Skills"],["progression","Progression"]].map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
       {message&&<p className={styles.message}>{message}</p>}
       <div className={styles.panel}>
       {tab==="overview"&&<><div className={styles.sectionTitle}><Sparkles/><div><h3>Current snapshot</h3><p>Values shown exactly as the public character service reports them.</p></div></div><div className={styles.statGrid}>{linked.stats.map(s=><article key={s.type+s.name}><span>{s.name||s.type}</span><strong>{fmt(s.value)}</strong>{s.effects?.slice(0,2).map(e=><small key={e}>{e}</small>)}</article>)}</div><div className={styles.collectionRow}>{linked.pet&&<article><PawPrint/><div><small>PET</small><b>{linked.pet.name}</b><span>Lv. {linked.pet.level}</span></div></article>}{linked.wing&&<article><Feather/><div><small>WINGS</small><b>{linked.wing.name}</b><span>{linked.wing.enchantLevel?("+"+linked.wing.enchantLevel):linked.wing.grade}</span></div></article>}</div></>}
       {tab==="equipment"&&<><div className={styles.sectionTitle}><Shield/><div><h3>Equipped gear</h3><p>{linked.equipment.length} slots returned by the official service.</p></div></div><div className={styles.gearGrid}>{linked.equipment.map((it,i)=><article key={it.slotPos+":"+it.id+":"+i}><span className={styles.itemIcon}>{it.icon?<img src={it.icon} alt=""/>:<Database/>}</span><div><small>{it.slotName||("Slot "+it.slotPos)} · {it.grade||"—"}</small><b>{it.name||("Item "+it.id)}</b><span>{it.exceedLevel?it.exceedLevel+"+":""}{it.enchantLevel?"+"+it.enchantLevel:""}</span></div></article>)}</div></>}
       {tab==="skills"&&<><div className={styles.sectionTitle}><Swords/><div><h3>Skills & Stigmas</h3><p>Only skills actually acquired by this character are shown, separated by type for faster review.</p></div></div><div className={styles.skillGroups}>{[["active","Active"],["passive","Passive"],["stigma","Stigma"]].map(([key,label])=><section className={styles.skillGroup} key={key}><header><div><span>{label.toUpperCase()}</span><h4>{label}</h4></div><b>{skillGroups[key].length}</b></header><div className={styles.skillGrid}>{skillGroups[key].map(s=><article key={s.id}><span className={styles.itemIcon}>{s.icon?<img src={s.icon} alt=""/>:<Sparkles/>}</span><div><small>{s.category||label}{s.equipped?" · EQUIPPED":""}</small><b>{s.name||("Skill "+s.id)}</b><span>Lv. {s.level}</span></div></article>)}{!skillGroups[key].length&&<p className={styles.skillEmpty}>No {label.toLowerCase()} skills acquired.</p>}</div></section>)}</div>{!acquired.length&&<p className={styles.message}>No acquired skills were returned for this character.</p>}</>}
       {tab==="progression"&&<><div className={styles.sectionTitle}><Database/><div><h3>Progression</h3><p>Titles, Daevanion board progress and public ranking records.</p></div></div><div className={styles.progressTop}><article><small>TITLES</small><strong>{linked.titles.owned}/{linked.titles.total||"—"}</strong></article><article><small>DAEVANION BOARDS</small><strong>{linked.daevanion.length}</strong></article><article><small>RANKINGS</small><strong>{linked.rankings.length}</strong></article></div><div className={styles.boardList}>{linked.daevanion.map(b=><article key={b.id}><span>{b.icon&&<img src={b.icon} alt=""/>}</span><div><b>{b.name||("Board "+b.id)}</b><small>{b.openNodes}/{b.totalNodes} nodes</small></div><strong>{b.openPercent}%</strong></article>)}</div></>}
       </div>
       <div className={styles.labNote}><b>LAB MODE</b><span>Character sync is read-only. Automatic import into Build Lab stays disabled until we finish verified slot/data mapping, so this test cannot corrupt your creator drafts.</span><a href="/build-lab">Open Build Lab →</a></div>
     </div>
   </section>:null}
 </main>;
}
