"use client";
import {useEffect,useMemo,useState} from "react";
import {Home,Menu,Search,RefreshCw,Link2,Shield,Swords,Sparkles,Feather,PawPrint,ExternalLink,Unlink,Database,LockKeyhole,Activity,Gauge,ChevronDown} from "lucide-react";
import styles from "./character.module.css";
const STORAGE="daevexus.character-link.v1";
const regions=[["naw","Global · NA West"],["nae","Global · NA East"],["eu","Global · Europe"],["sa","Global · South America"],["asia","Global · Asia"],["tw","Taiwan · Lab"]];
const fmt=n=>new Intl.NumberFormat("en-US").format(Number(n)||0);
const race=id=>Number(id)===1?"Elyos":Number(id)===2?"Asmodian":"Unknown";
const skillRow=(meta,level)=>meta?.levels?.find(row=>Number(row.level)===Number(level))||null;
const range=(a,b)=>a==null&&b==null?"—":a==null?String(b):b==null?String(a):String(a)===String(b)?String(a):a+" – "+b;
function StatRows({rows,empty="No recorded rows."}){return rows?.length?<div className={styles.detailStats}>{rows.map((row,i)=><div key={(row.id||row.name||"row")+i}><span>{row.name||row.id||"Stat"}</span><strong>{row.minValue?row.minValue+" – ":""}{row.value||"—"}</strong>{row.extra&&row.extra!=="0"&&<small>Enhancement share {row.extra}</small>}</div>)}</div>:<p className={styles.emptyLine}>{empty}</p>;}
export default function MyCharacter(){
 const[region,setRegion]=useState("naw"),[name,setName]=useState(""),[serverId,setServerId]=useState(""),[profileUrl,setProfileUrl]=useState(""),[results,setResults]=useState([]),[linked,setLinked]=useState(null),[syncedAt,setSyncedAt]=useState(""),[tab,setTab]=useState("overview"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const[selectedSkill,setSelectedSkill]=useState(null),[skillMeta,setSkillMeta]=useState(null),[skillBusy,setSkillBusy]=useState(false),[skillError,setSkillError]=useState("");
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const data=JSON.parse(raw);if(data?.character){setLinked(data.character);setSyncedAt(data.syncedAt||"");setRegion(data.character.region||"naw");}}}catch{}},[]);
 const itemLevel=useMemo(()=>linked?.stats?.find(s=>String(s.type).toLowerCase()==="itemlevel")?.value||0,[linked]);
 const acquired=useMemo(()=>linked?.skills?.filter(s=>s.acquired!==false)||[],[linked]);
 const weaponDamage=linked?.weaponDamage;
 const persist=(character,time)=>{setLinked(character);setSyncedAt(time||"");setSelectedSkill(null);setSkillMeta(null);try{localStorage.setItem(STORAGE,JSON.stringify({character,syncedAt:time}));}catch{}};
 async function search(event){event?.preventDefault();setBusy(true);setMessage("");setResults([]);try{const q=new URLSearchParams({region,keyword:name.trim()});if(serverId)q.set("serverId",serverId);const res=await fetch("/api/character-search?"+q,{cache:"no-store"}),data=await res.json();if(!data.ok)throw new Error(data.error);const matches=data.results||[];if(matches.length===1){await syncRef(matches[0]);return;}setResults(matches);if(!matches.length)setMessage(`No exact character named "${name.trim()}" was found in this region${serverId?` / server ${serverId}`:""}. Check the spelling or use the official profile URL.`);else setMessage("More than one character has this exact name. Choose the correct server.");}catch(e){setMessage(e.message||"Search failed.");}finally{setBusy(false);}}
 async function syncRef(ref){setBusy(true);setMessage("");try{const q=new URLSearchParams({region:ref.region,serverId:String(ref.serverId),characterId:ref.characterId});const res=await fetch("/api/character-sync?"+q,{cache:"no-store"}),data=await res.json();if(!data.ok)throw new Error(data.error);persist(data.character,data.syncedAt);setResults([]);setTab("overview");}catch(e){setMessage(e.message||"Sync failed.");}finally{setBusy(false);}}
 async function linkUrl(event){event?.preventDefault();setBusy(true);setMessage("");try{const res=await fetch("/api/character-sync?"+new URLSearchParams({profileUrl}),{cache:"no-store"}),data=await res.json();if(!data.ok)throw new Error(data.error);persist(data.character,data.syncedAt);setResults([]);setTab("overview");}catch(e){setMessage(e.message||"Could not link this profile.");}finally{setBusy(false);}}
 async function inspectSkill(skill){setSelectedSkill(skill);setSkillMeta(null);setSkillError("");setSkillBusy(true);try{const res=await fetch("/api/skill-description/"+skill.id,{cache:"no-store"}),data=await res.json();if(!res.ok||data.error)throw new Error(data.error||"No reference metadata.");setSkillMeta(data);}catch(e){setSkillError(e.message||"Skill metadata unavailable.");}finally{setSkillBusy(false);}}
 const unlink=()=>{setLinked(null);setSyncedAt("");setTab("overview");setSelectedSkill(null);setSkillMeta(null);try{localStorage.removeItem(STORAGE);}catch{}};
 const metaLevel=selectedSkill?skillRow(skillMeta,selectedSkill.level):null;
 return <main className={styles.page}>
   <header className={styles.top}><a href="/?menu=open" aria-label="Open DAEVEXUS menu"><Menu/></a><div><small>DAEVEXUS · CHARACTER LAB</small><h1>My Character</h1></div><a href="/" aria-label="Home"><Home/></a></header>
   {!linked?<section className={styles.connect}>
     <div className={styles.intro}><span>PUBLIC PROFILE LINK</span><h2>Bring your Daeva into DAEVEXUS.</h2><p>Link a public AION 2 character profile and sync the information NC exposes: level, class, combat power, stats, equipped gear, skills, Pet, Wings and progression.</p><div className={styles.safe}><LockKeyhole/><p><b>No NC/PURPLE password.</b> DAEVEXUS reads only the public character information already exposed by the official character service.</p></div></div>
     <div className={styles.forms}>
       <form onSubmit={search} className={styles.box}><div className={styles.boxTitle}><Search/><div><b>Search exact character</b><small>Exact name only · no similar-name list</small></div></div><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Character name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Exact character name" minLength={2}/></label><label>Server ID <small>optional</small><input value={serverId} onChange={e=>setServerId(e.target.value.replace(/\D/g,""))} inputMode="numeric" placeholder="e.g. 1201"/></label><button disabled={busy||name.trim().length<2}>{busy?"Checking…":"Find exact character"}</button></form>
       <form onSubmit={linkUrl} className={styles.box}><div className={styles.boxTitle}><Link2/><div><b>Link from profile URL</b><small>Best option for direct linking</small></div></div><label>Official character URL<textarea value={profileUrl} onChange={e=>setProfileUrl(e.target.value)} placeholder="https://aion2.plaync.com/en-us/characters/… or https://tw.ncsoft.com/aion2/characters/…"/></label><button disabled={busy||!profileUrl.trim()}>{busy?"Syncing…":"Link & sync"}</button><p className={styles.mini}>Open your character on the official AION 2 Character Info page, copy the URL and paste it here.</p></form>
     </div>
     {message&&<p className={styles.message}>{message}</p>}
     {!!results.length&&<div className={styles.results}><div className={styles.resultsHead}><b>Exact-name matches</b><span>{results.length}</span></div>{results.map(r=><button key={r.serverId+":"+r.characterId} onClick={()=>syncRef(r)} disabled={busy}><span className={styles.avatar}>{r.profileImage?<img src={r.profileImage} alt=""/>:<Shield/>}</span><span><b>{r.name}</b><small>Lv. {r.level} · {r.serverName||("Server "+r.serverId)} · {race(r.race)}</small></span><strong>LINK</strong></button>)}</div>}
   </section>:<section className={styles.dashboard}>
     <aside className={styles.profile}>
       <div className={styles.portrait}>{linked.profile.image?<img src={linked.profile.image} alt=""/>:<Shield/>}</div><span className={styles.region}>{regions.find(x=>x[0]===linked.region)?.[1]||linked.region}</span><h2>{linked.profile.name}</h2><p>{linked.profile.className||"Class pending"} · Lv. {linked.profile.level} · {race(linked.profile.raceId)}</p><small>{linked.profile.serverName||("Server "+linked.serverId)}{linked.profile.guildName?" · "+linked.profile.guildName:""}</small>
       <div className={styles.sync}><button onClick={()=>syncRef(linked)} disabled={busy}><RefreshCw/> {busy?"Deep syncing…":"Deep sync now"}</button><a href={linked.profileUrl} target="_blank" rel="noreferrer">Official <ExternalLink/></a></div>
       <button className={styles.unlink} onClick={unlink}><Unlink/> Unlink this character</button>
       <div className={styles.syncTime}>Last sync<br/><b>{syncedAt?new Date(syncedAt).toLocaleString():"—"}</b></div>
     </aside>
     <div className={styles.content}>
       <div className={styles.metrics}><article><small>COMBAT POWER</small><strong>{fmt(linked.profile.combatPower)}</strong></article><article><small>LEVEL</small><strong>{linked.profile.level||"—"}</strong></article><article><small>ITEM LEVEL</small><strong>{itemLevel?fmt(itemLevel):"—"}</strong></article><article><small>WEAPON ATTACK</small><strong>{weaponDamage?range(weaponDamage.min,weaponDamage.max):"—"}</strong></article><article><small>EQUIPMENT</small><strong>{linked.equipment.length}</strong></article><article><small>SKILLS</small><strong>{acquired.length}</strong></article></div>
       {linked.levelSources?.mismatch&&<div className={styles.crosscheck}><Gauge/><div><b>Level cross-check detected a difference.</b><span>Profile API: Lv. {linked.levelSources.profile} · Exact Search API: Lv. {linked.levelSources.search} · Showing Lv. {linked.levelSources.level}. Both raw official readings are preserved.</span></div></div>}
       <nav className={styles.tabs}>{[["overview","Overview"],["equipment","Equipment"],["skills","Skills"],["progression","Progression"]].map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
       {message&&<p className={styles.message}>{message}</p>}
       <div className={styles.panel}>
       {tab==="overview"&&<><div className={styles.sectionTitle}><Activity/><div><h3>Current official snapshot</h3><p>Raw current values returned by the public character services. No combat formula is invented.</p></div></div><div className={styles.statGrid}>{linked.stats.map(s=><article key={s.type+s.name}><span>{s.name||s.type}</span><strong>{fmt(s.value)}</strong>{s.effects?.map(e=><small key={e}>{e}</small>)}</article>)}</div><div className={styles.collectionRow}>{linked.pet&&<article><PawPrint/><div><small>PET</small><b>{linked.pet.name}</b><span>Lv. {linked.pet.level}</span></div></article>}{linked.wing&&<article><Feather/><div><small>WINGS</small><b>{linked.wing.name}</b><span>{linked.wing.enchantLevel?("+"+linked.wing.enchantLevel):linked.wing.grade}</span></div></article>}</div><div className={styles.coverage}><span>Equipment details <b>{linked.sync?.equipmentDetails?.loaded??0}/{linked.sync?.equipmentDetails?.total??linked.equipment.length}</b></span><span>Daevanion details <b>{linked.sync?.daevanionDetails?.loaded??0}/{linked.sync?.daevanionDetails?.total??linked.daevanion.length}</b></span><span>Level cross-check <b>{linked.sync?.levelCrossChecked?"OK":"Pending"}</b></span></div>{linked.sync?.warnings?.length>0&&<details className={styles.warnings}><summary>Sync notes ({linked.sync.warnings.length}) <ChevronDown/></summary>{linked.sync.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}</>}
       {tab==="equipment"&&<><div className={styles.sectionTitle}><Shield/><div><h3>Equipped gear · live copy</h3><p>Every returned slot plus the detailed rolls, stones and weapon values that NC exposes.</p></div></div><div className={styles.gearGrid}>{linked.equipment.map((it,i)=><details className={styles.gearCard} key={it.slotPos+":"+it.id+":"+i}><summary><span className={styles.itemIcon}>{it.icon?<img src={it.icon} alt=""/>:<Database/>}</span><div><small>{it.slotName||("Slot "+it.slotPos)} · {it.grade||"—"}</small><b>{it.name||("Item "+it.id)}</b><span>{it.exceedLevel?it.exceedLevel+"+":""}{it.enchantLevel?"+"+it.enchantLevel:""}</span></div><ChevronDown className={styles.chevron}/></summary><div className={styles.itemDetail}>{it.detail?<><div className={styles.itemFacts}><span>Item Lv. <b>{it.detail.itemLevel||"—"}</b></span><span>Equip Lv. <b>{it.detail.equipLevel||"—"}</b></span><span>Max enchant <b>+{it.detail.maxEnchantLevel||0}</b></span></div><h4>Main stats</h4><StatRows rows={it.detail.mainStats}/><h4>Current extra stats</h4><StatRows rows={it.detail.subStats}/>{it.detail.subSkills?.length>0&&<><h4>Item skills</h4>{it.detail.subSkills.map(s=><p className={styles.itemLine} key={s.id}>{s.name} · Lv. {s.level}</p>)}</>}{it.detail.magicStones?.length>0&&<><h4>Magic stones</h4>{it.detail.magicStones.map((s,j)=><p className={styles.itemLine} key={j}>{s.name} {s.value} · {s.grade}</p>)}</>}{it.detail.godStones?.length>0&&<><h4>Godstones</h4>{it.detail.godStones.map((s,j)=><p className={styles.itemLine} key={j}>{s.name} · {s.desc}</p>)}</>}:<p className={styles.emptyLine}>Detailed item roll was not returned during this sync.</p>}</div></details>)}</div></>}
       {tab==="skills"&&<><div className={styles.sectionTitle}><Swords/><div><h3>Skills & Stigmas · current character state</h3><p>Level, acquired state and equipped state come from your linked character. Tap a skill to inspect reference metadata at that exact level.</p></div></div><div className={styles.skillGrid}>{linked.skills.map(s=><button type="button" className={selectedSkill?.id===s.id?styles.skillSelected:""} key={s.id} onClick={()=>inspectSkill(s)}><span className={styles.itemIcon}>{s.icon?<img src={s.icon} alt=""/>:<Sparkles/>}</span><div><small>{s.category||"Skill"}{s.equipped?" · EQUIPPED":""}</small><b>{s.name||("Skill "+s.id)}</b><span>Lv. {s.level}{!s.acquired?" · Locked":""}</span></div></button>)}</div>{selectedSkill&&<section className={styles.skillInspector}><div className={styles.inspectorHead}><div><span>OFFICIAL CHARACTER STATE</span><h4>{selectedSkill.name}</h4><p>Current Lv. {selectedSkill.level} · {selectedSkill.category||"Skill"} · {selectedSkill.equipped?"Equipped":"Not equipped"}</p></div>{skillBusy&&<RefreshCw className={styles.spin}/>}</div>{skillError&&<p className={styles.emptyLine}>{skillError}</p>}{skillMeta&&<><div className={styles.referenceFlag}>REFERENCE METADATA · PENDING GLOBAL CLIENT VERIFICATION</div><div className={styles.skillNumbers}><article><small>DAMAGE</small><strong>{range(metaLevel?.dmg_min,metaLevel?.dmg_max)}</strong></article><article><small>HEALING</small><strong>{range(metaLevel?.heal_min,metaLevel?.heal_max)}</strong></article><article><small>COOLDOWN</small><strong>{metaLevel?.cooldown!=null?metaLevel.cooldown+" s":"—"}</strong></article><article><small>MP COST</small><strong>{metaLevel?.cost_mp??"—"}</strong></article></div><p className={styles.skillDesc}>{skillMeta.description||"No description."}</p></>}</section>}</>}
       {tab==="progression"&&<><div className={styles.sectionTitle}><Database/><div><h3>Progression · current public state</h3><p>Titles, board completion and detailed open Daevanion effects when available.</p></div></div><div className={styles.progressTop}><article><small>TITLES</small><strong>{linked.titles.owned}/{linked.titles.total||"—"}</strong></article><article><small>DAEVANION BOARDS</small><strong>{linked.daevanion.length}</strong></article><article><small>RANKINGS</small><strong>{linked.rankings.length}</strong></article></div><div className={styles.boardList}>{linked.daevanion.map(b=><details key={b.id}><summary><span>{b.icon&&<img src={b.icon} alt=""/>}</span><div><b>{b.name||("Board "+b.id)}</b><small>{b.openNodes}/{b.totalNodes} nodes</small></div><strong>{b.openPercent}%</strong></summary>{b.detail&&<div className={styles.boardDetail}><h4>Open stat effects</h4>{b.detail.openStatEffects?.length?b.detail.openStatEffects.map((x,i)=><p key={i}>{x}</p>):<p>None returned.</p>}<h4>Open skill effects</h4>{b.detail.openSkillEffects?.length?b.detail.openSkillEffects.map((x,i)=><p key={i}>{x}</p>):<p>None returned.</p>}</div>}</details>)}</div></>}
       </div>
       <div className={styles.labNote}><b>LAB MODE</b><span>Deep sync is read-only. Official live state is separated from reference metadata. Build Lab import remains disabled until slot mapping is verified against the Global client.</span><a href="/build-lab">Open Build Lab →</a></div>
     </div>
   </section>}
 </main>;
}
