import test from 'node:test';import assert from 'node:assert/strict';
import {SLOTS,variant,normalize,newDoc,summary,slotsFor,compatible,clone,parseValue,shareCode,readShare,toggleNode,boardNodes} from '../public/build-lab-assets/model.mjs';
import {boundedInt,pairs,petLevels,collectionRows,recordStatus,detailForSkill,buildChecks,compareSystems} from '../public/build-lab-assets/review-model.mjs';
const skill={id:'12010000',name:'Reference strike',type:'active'};
const c={classes:[{slug:'templar',name:'Templar',mainTypes:['longsword'],offTypes:['shield'],skills:[skill]},{slug:'gladiator',name:'Gladiator',mainTypes:['greatsword','polearm'],offTypes:[],skills:[]}],equipment:[{id:'210000001',name:'Reference sword',region:'GLOBAL',category:'longsword',requiredLevel:'60',stats:[{label:'Attack',value:'10'},{label:'HP',value:'100'}]},{id:'210000002',name:'Reference helm',region:'GLOBAL',category:'helmet',requiredLevel:'1',stats:[{label:'HP',value:'50'}]}],wings:[{id:'500000001',name:'Wings',region:'KR_TW',faction:'Elyos',stats:[{label:'HP',value:'40'}]}],pets:[{id:'600000001',name:'Pet',region:'KR_TW',detail:{baseStats:{columns:['Level','HP','Attack'],rows:[[1,'10','2'],[10,'100','20']]}}}],arcana:[{id:'810000001',name:'Card',region:'GLOBAL',stats:[{label:'Attack',value:'3'}]}],boards:{Templar:{Nezekan:[[1,1,'Start','Start',0,1],[1,2,'Attack','Common',1,0],[1,3,'HP','Rare',2,0]]}}};
test('pet preview uses the exact selected recorded level',()=>assert.deepEqual(collectionRows(c.pets[0],'pets',10),[{label:'HP',value:'100'},{label:'Attack',value:'20'}]));
test('unknown pet level is not interpolated',()=>assert.deepEqual(collectionRows(c.pets[0],'pets',2),[]));
test('pet level selector is sorted and deduplicated',()=>assert.deepEqual(petLevels({detail:{baseStats:{rows:[[10],[1],[1],['bad']]}}}),[1,10]));
test('missing pet details produce no invented values',()=>assert.deepEqual(petLevels({}),[]));
test('stat pair normalization preserves zero',()=>assert.deepEqual(pairs([['HP',0],null,{label:'',value:3}]),[{label:'HP',value:'0'}]));
test('malformed wing value cannot be shown as numeric bonus',()=>assert.equal(recordStatus({value:'HP'}),'unknown'));
test('recorded ranges are labelled as ranges',()=>assert.equal(recordStatus({value:'3 ~ 9'}),'range'));
test('an exact percentage is a fixed record',()=>assert.equal(recordStatus({value:'2.5%'}),'fixed'));
test('integer planning limits reject NaN',()=>assert.equal(boundedInt('no',1,100,45),45));
test('integer planning input rounds down within limits',()=>assert.equal(boundedInt(3.9,1,100),3));
test('skill detail adds recorded HP and DP costs',()=>{const r=detailForSkill({levels:[{level:1,cost_hp:2,cost_dp:3}]},1);assert.ok(r.rows.some(x=>x.label==='HP cost'&&x.value==='2'));assert.ok(r.rows.some(x=>x.label==='DP cost'&&x.value==='3'));});
test('zero HP and DP costs do not create redundant rows',()=>assert.equal(detailForSkill({levels:[{level:1,cost_hp:0,cost_dp:0}]},1).rows.length,0));
test('instant casting is readable, not 0 seconds',()=>assert.equal(detailForSkill({levels:[{level:1,casting_time:0}]},1).rows[0].value,'Instant'));
test('identical damage bounds become one damage row',()=>assert.deepEqual(detailForSkill({levels:[{level:1,dmg_min:51,dmg_max:51}]},1).rows,[{label:'Damage',value:'51'}]));
test('different damage bounds remain an explicit range',()=>assert.deepEqual(detailForSkill({levels:[{level:1,dmg_min:51,dmg_max:78}]},1).rows,[{label:'Damage',value:'51 – 78'}]));
test('skill flat fallback remains available without a level table',()=>assert.deepEqual(detailForSkill({stats:[{label:'Range',value:'4m'}]},1).rows,[{label:'Range',value:'4m'}]));
test('a required equipment level is surfaced',()=>{const v=variant();v.gear.mainHand={id:'210000001'};assert.ok(buildChecks(v,c).some(x=>x.label.includes('requires reference level 60')));});
test('unavailable saved gear is diagnosed, not deleted',()=>{const v=variant();v.gear.helmet={id:'missing'};assert.equal(buildChecks(v,c).length,1);assert.equal(v.gear.helmet.id,'missing');});
test('invalid class skill is diagnosed',()=>{const v=variant();v.skills['99999999']={level:1,spec:{}};assert.ok(buildChecks(v,c).some(x=>x.label.includes('not part')));});
test('unselected unlocked specialty is identified',()=>{const v=variant();v.skills[skill.id]={level:8,spec:{}};const cache={[skill.id]:{levels:[{level:8}],specialties:[{level:8,description:'a'},{level:8,description:'b'}]}};assert.ok(buildChecks(v,c,cache).some(x=>x.label.includes('choose a specialization')));});
test('wing faction mismatch is diagnosed',()=>{const v=variant();v.faction='Asmodians';v.wingId='500000001';assert.ok(buildChecks(v,c).some(x=>x.label.includes('different faction')));});
test('budget checks do not confuse costs with bonuses',()=>{const v=variant();v.paths.Nezekan=['1,2','1,3'];v.budgets.Nezekan=1;assert.ok(buildChecks(v,c).some(x=>x.label.includes('2 over')));assert.equal(summary(v,c).rows.length,0);});
test('comparison includes changed skill levels',()=>{const a=variant(),b=clone(a);a.skills[skill.id]={level:1,spec:{}};b.skills[skill.id]={level:8,spec:{}};assert.ok(compareSystems(a,b,c).some(x=>x.system==='Skills'&&x.a==='Lv. 1'&&x.b==='Lv. 8'));});
test('comparison includes target-only changes on the same item',()=>{const a=variant(),b=clone(a);a.gear.mainHand={id:'210000001',enchant:0,note:''};b.gear.mainHand={id:'210000001',enchant:10,note:'HP'};assert.equal(compareSystems(a,b,c).filter(x=>x.system==='Equipment').length,2);});
test('same count with different board nodes still compares',()=>{const a=variant(),b=clone(a);a.paths.Nezekan=['1,2'];b.paths.Nezekan=['1,3'];assert.ok(compareSystems(a,b,c).some(x=>x.system==='Daevanion'));});
test('identical configurations create no spurious changes',()=>{const a=variant();assert.deepEqual(compareSystems(a,clone(a),c),[]);});
test('percentage sums and malformed values remain distinct',()=>{assert.deepEqual(parseValue('2 + 3%'),{n:5,unit:'%'});assert.equal(parseValue('3 ~ 9'),null);});
test('cross-region pet bonus stays excluded from Global totals',()=>{const v=variant();v.petId='600000001';assert.equal(summary(v,c).rows.length,0);assert.ok(summary(v,c).excluded.length);});
test('alternate main weapon does not enable an off-hand slot',()=>{const v=variant();v.classSlug='gladiator';assert.ok(!slotsFor(v,c).some(s=>s.id==='offHand'));});
test('old Lab saved format stays compatible',()=>{const d=newDoc();d.variants[0].notes='Español 🎮';d.variants[0].gear.helmet={id:'210000002',enchant:0,note:'Test'};const n=normalize(d);assert.equal(n.variants[0].notes,d.variants[0].notes);assert.equal(n.variants[0].gear.helmet.id,'210000002');});
test('Unicode share round-trip preserves notes',async()=>{const d=newDoc();d.variants[0].notes='Español 🎮 <script>plain text</script>';assert.equal((await readShare(await shareCode(d))).variants[0].notes,d.variants[0].notes);});
test('path builder keeps connected nodes within budget',()=>{const v=variant();const nodes=boardNodes(v,c,'Nezekan');assert.deepEqual(toggleNode(nodes,[],'1,3',3),['1,3','1,2']);assert.throws(()=>toggleNode(nodes,[],'1,3',2));});
test('selected skills with unloaded details are explicitly unchecked',()=>{const v=variant();v.skills[skill.id]={level:8,spec:{}};assert.ok(buildChecks(v,c).some(x=>x.label.includes('open the skill')));});
test('skill requirements above planned level are reported',()=>{const v=variant();v.skills[skill.id]={level:8,spec:{}};assert.ok(buildChecks(v,c,{[skill.id]:{requiredLevel:60}}).some(x=>x.label.includes('requires reference level 60')));});
test('class and planned level changes are included in comparison',()=>{const a=variant(),b=clone(a);b.classSlug='gladiator';b.level=50;assert.equal(compareSystems(a,b,c).filter(x=>x.system==='Character').length,2);});
test('equal-cost paths show differing node identities',()=>{const a=variant(),b=clone(a);a.paths.Nezekan=['1,2'];b.paths.Nezekan=['1,3'];const r=compareSystems(a,b,c).find(x=>x.system==='Daevanion');assert.ok(r.a.includes('[1,2]'));assert.ok(r.b.includes('[1,3]'));});
test('budget-only edits appear in comparison',()=>{const a=variant(),b=clone(a);a.paths.Nezekan=['1,2'];b.paths.Nezekan=['1,2'];b.budgets.Nezekan=5;assert.ok(compareSystems(a,b,c).some(x=>x.label.includes('budget')));});
