import test from "node:test";import assert from "node:assert/strict";import {parseProfileUrl,regionFromServerId,normalizeCharacter,normalizeSearchRow,exactCharacterName,resolveOfficialLevel,normalizeEquippedItemDetail,normalizeDaevanionDetail,weaponDamageFromEquipment} from "../app/my-character/character-model.mjs";
test("maps Global server ranges to shards",()=>{assert.equal(regionFromServerId(1101),"nae");assert.equal(regionFromServerId(1201),"naw");assert.equal(regionFromServerId(1301),"eu");assert.equal(regionFromServerId(1401),"sa");assert.equal(regionFromServerId(1501),"asia");assert.equal(regionFromServerId(2004),"");});
test("parses official Taiwan profile URL",()=>{const r=parseProfileUrl("https://tw.ncsoft.com/aion2/characters/2004/abc%3D");assert.equal(r.region,"tw");assert.equal(r.serverId,2004);assert.equal(r.characterId,"abc=");});
test("parses official Global profile URL and derives shard",()=>{const r=parseProfileUrl("https://aion2.plaync.com/en-us/characters/1201/xyz%3D");assert.equal(r.region,"naw");assert.equal(r.characterId,"xyz=");});
test("rejects lookalike and unrelated profile hosts",()=>{assert.throws(()=>parseProfileUrl("https://evil.example/aion2.plaync.com/en-us/characters/1201/abc"));assert.throws(()=>parseProfileUrl("not a url"));});
test("normalizes official character data without inventing missing values",()=>{const info={profile:{characterName:"Daeva",characterLevel:45,className:"Gladiator",raceId:1,serverName:"Test",combatPower:12345},stat:{statList:[{type:"STR",name:"Power",value:17}]},daevanion:{boardList:[{id:1,name:"Nezekan",openNodeCount:2,totalNodeCount:10,openPercent:20}]},title:{ownedCount:3,totalCount:9},ranking:{rankingList:[]}};const eq={equipment:{equipmentList:[{slotPos:1,slotPosName:"Weapon",id:99,name:"Blade",grade:"Unique",enchantLevel:10,icon:"Icon_Test.png"}]},skill:{skillList:[{id:100,name:"Strike",category:"Active",skillLevel:5,acquired:1,equip:1}]},petwing:{pet:{id:2,name:"Pet",level:3,icon:"Pet.png"},wing:{id:3,name:"Wing",grade:"Unique",enchantLevel:4,icon:"Wing.png"}}};const c=normalizeCharacter(info,eq,{region:"naw",serverId:1201,characterId:"id="});assert.equal(c.profile.name,"Daeva");assert.equal(c.profile.combatPower,12345);assert.equal(c.equipment[0].enchantLevel,10);assert.equal(c.skills[0].level,5);assert.equal(c.pet.level,3);assert.equal(c.wing.enchantLevel,4);assert.equal(c.stats[0].value,17);});
test("search normalization keeps official identity",()=>{const r=normalizeSearchRow({serverId:1201,characterId:"abc%3D",name:"<strong>Hero</strong>",serverName:"West",race:2,level:50},"naw");assert.equal(r.name,"Hero");assert.equal(r.characterId,"abc=");assert.equal(r.profileUrl.includes("/1201/"),true);});

test("matches character names exactly without fuzzy results",()=>{assert.equal(exactCharacterName("Mixi","Mixi"),true);assert.equal(exactCharacterName("MIXI","mixi"),true);assert.equal(exactCharacterName("Mixi "," Mixi"),true);assert.equal(exactCharacterName("Mixii","Mixi"),false);assert.equal(exactCharacterName("TheMixi","Mixi"),false);});

test("resolves level from two official readings without hiding disagreement",()=>{const r=resolveOfficialLevel(19,27);assert.equal(r.level,27);assert.equal(r.profile,19);assert.equal(r.search,27);assert.equal(r.mismatch,true);assert.equal(r.resolution,"highest-official-reading");});
test("matching official level readings are marked as agreement",()=>{const r=resolveOfficialLevel(31,31);assert.equal(r.level,31);assert.equal(r.mismatch,false);assert.equal(r.resolution,"official-agreement");});
test("equipped item detail preserves live weapon damage and rolls as strings",()=>{const d=normalizeEquippedItemDetail({id:9,name:"Blade",level:88,equipLevel:25,enchantLevel:7,maxEnchantLevel:20,mainStats:[{id:"WeaponFixingDamage",name:"Attack",minValue:"321",value:"444",extra:"80"}],subStats:[{id:"Critical",name:"Critical Hit",value:"60"}],magicStoneStat:[{name:"HP",value:"+80"}]});assert.equal(d.mainStats[0].minValue,"321");assert.equal(d.mainStats[0].value,"444");assert.equal(d.subStats[0].value,"60");assert.equal(d.magicStones[0].value,"+80");});
test("weapon damage is read from official equipped-item detail only",()=>{const equipment=[{id:9,name:"Blade",detail:normalizeEquippedItemDetail({id:9,name:"Blade",mainStats:[{id:"WeaponFixingDamage",name:"Attack",minValue:"321",value:"444",extra:"80"}]})}];assert.deepEqual(weaponDamageFromEquipment(equipment),{itemId:9,itemName:"Blade",min:"321",max:"444",extra:"80"});});
test("Daevanion detail keeps open effects and node state",()=>{const d=normalizeDaevanionDetail({nodeList:[{nodeId:1,name:"Attack",open:1,row:2,col:3,effectList:[{desc:"Attack +10"}]}],openSkillEffectList:[{desc:"Skill +1"}],openStatEffectList:[{desc:"HP +100"}]},{id:71,name:"Nezekan"});assert.equal(d.nodes[0].open,true);assert.deepEqual(d.nodes[0].effects,["Attack +10"]);assert.deepEqual(d.openSkillEffects,["Skill +1"]);assert.deepEqual(d.openStatEffects,["HP +100"]);});
