const source = {
  name: "DAEVEXUS reviewed Global client-data cross-check",
  region: "Global 1.0.21.0",
  capturedAt: "2026-09-30",
  official: false,
};

const icon = (id) => `https://aion2hub.com/api/icon/items/${id}`;
const details = (kind) => [
  {label: "Slot", value: kind},
  {label: "Region/version", value: "AION 2 Global 1.0.21.0"},
];

export default [
  {
    id: "311030001",
    name: "Revelation Amulet",
    group: "Accessories",
    category: "Amulet",
    grade: "Unique",
    itemLevel: "65",
    requiredLevel: "1",
    equipType: "Amulet",
    itemType: "Accessories",
    icon: icon("311030001"),
    stats: [
      {label: "Weapon Damage Boost", value: "10%"},
      {label: "Perfect Chance", value: "5%"},
      {label: "Penetration", value: "700"},
      {label: "Power Shard Damage Bonus", value: "40"},
    ],
    details: details("Amulet"),
    source,
  },
  {
    id: "311040001",
    name: "Revelation Amulet",
    group: "Accessories",
    category: "Amulet",
    grade: "Epic",
    itemLevel: "36",
    requiredLevel: "1",
    equipType: "Amulet",
    itemType: "Accessories",
    icon: icon("311040001"),
    stats: [
      {label: "Weapon Damage Boost", value: "7.5%"},
      {label: "Penetration", value: "400"},
      {label: "Power Shard Damage Bonus", value: "10"},
    ],
    details: details("Amulet"),
    source,
  },
  {
    id: "311050001",
    name: "Revelation Amulet",
    group: "Accessories",
    category: "Amulet",
    grade: "Rare",
    itemLevel: "13",
    requiredLevel: "1",
    equipType: "Amulet",
    itemType: "Accessories",
    icon: icon("311050001"),
    stats: [
      {label: "Weapon Damage Boost", value: "5%"},
      {label: "Penetration", value: "100"},
    ],
    details: details("Amulet"),
    source,
  },
  {
    id: "311030002",
    name: "Fierce Battle Amulet",
    group: "Accessories",
    category: "Amulet",
    grade: "Unique",
    itemLevel: "65",
    requiredLevel: "1",
    equipType: "Amulet",
    itemType: "Accessories",
    icon: icon("311030002"),
    stats: [
      {label: "PvP Damage Boost", value: "20%"},
      {label: "Perfect Chance", value: "5%"},
      {label: "Penetration", value: "700"},
      {label: "Power Shard Damage Bonus", value: "40"},
    ],
    details: details("Amulet"),
    source,
  },
  {
    id: "311040002",
    name: "Fierce Battle Amulet",
    group: "Accessories",
    category: "Amulet",
    grade: "Epic",
    itemLevel: "36",
    requiredLevel: "1",
    equipType: "Amulet",
    itemType: "Accessories",
    icon: icon("311040002"),
    stats: [
      {label: "PvP Damage Boost", value: "15%"},
      {label: "Penetration", value: "400"},
      {label: "Power Shard Damage Bonus", value: "10"},
    ],
    details: details("Amulet"),
    source,
  },
  {
    id: "311050002",
    name: "Fierce Battle Amulet",
    group: "Accessories",
    category: "Amulet",
    grade: "Rare",
    itemLevel: "13",
    requiredLevel: "1",
    equipType: "Amulet",
    itemType: "Accessories",
    icon: icon("311050002"),
    stats: [
      {label: "PvP Damage Boost", value: "10%"},
      {label: "Penetration", value: "100"},
    ],
    details: details("Amulet"),
    source,
  },
  {
    id: "215230001",
    name: "Noble Belt",
    group: "Armor",
    category: "Belt",
    grade: "Unique",
    itemLevel: "65",
    requiredLevel: "1",
    equipType: "Belt",
    itemType: "Armor",
    icon: icon("215230001"),
    stats: [
      {label: "HP Potion Recovery increase", value: "30%"},
      {label: "Regeneration", value: "5%"},
      {label: "HP", value: "1100"},
      {label: "Defense", value: "500"},
    ],
    details: details("Belt"),
    source,
  },
  {
    id: "215240001",
    name: "Noble Belt",
    group: "Armor",
    category: "Belt",
    grade: "Epic",
    itemLevel: "36",
    requiredLevel: "1",
    equipType: "Belt",
    itemType: "Armor",
    icon: icon("215240001"),
    stats: [
      {label: "HP Potion Recovery increase", value: "20%"},
      {label: "HP", value: "600"},
      {label: "Defense", value: "200"},
    ],
    details: details("Belt"),
    source,
  },
  {
    id: "215250001",
    name: "Noble Belt",
    group: "Armor",
    category: "Belt",
    grade: "Rare",
    itemLevel: "13",
    requiredLevel: "1",
    equipType: "Belt",
    itemType: "Armor",
    icon: icon("215250001"),
    stats: [
      {label: "HP Potion Recovery increase", value: "10%"},
      {label: "HP", value: "100"},
    ],
    details: details("Belt"),
    source,
  },
  {
    id: "310900001",
    name: "Clash Rune",
    group: "Accessories",
    category: "Rune",
    grade: "Special",
    itemLevel: "40",
    requiredLevel: "10",
    equipType: "Rune",
    itemType: "Accessories",
    icon: icon("310900001"),
    stats: [
      {label: "PvE Damage Tolerance", value: "0.5%"},
      {label: "PvE Damage Boost", value: "0.5%"},
      {label: "Penetration", value: "100"},
      {label: "Combat Speed", value: "1%"},
      {label: "Multi-hit Chance", value: "1%"},
    ],
    details: details("Rune"),
    source,
  },
];
