// Individual sanctuary illustrations; pets without a scene retain their reference portrait.
const petScenes = {
  "1058": {src:"/pets/pet-1058.webp",alt:"Black Smoke Murute in smoldering coal field beneath an ash-black sky, twisting smoke pillars and glowing embers",position:"center 42%",mobilePosition:"center 35%"},
  "1059": {src:"/pets/pet-1059.webp",alt:"Giant Bee in sunflower terrace beside terracotta hives, amber honey trickles and warm noon haze",position:"center 42%",mobilePosition:"center 35%"},
  "1060": {src:"/pets/pet-1060.webp",alt:"Starturtle in shallow sapphire river beside smooth pink granite boulders and a fallen flowering branch",position:"center 42%",mobilePosition:"center 35%"},
  "1061": {src:"/pets/pet-1061.webp",alt:"Slime in mosaic fountain courtyard with clear dancing water, cobalt tiles and climbing white jasmine",position:"center 42%",mobilePosition:"center 35%"},
  "1062": {src:"/pets/pet-1062.webp",alt:"Contaminated Slime in abandoned copper alchemy workshop with stained vessels, chartreuse light and oxidized pipes",position:"center 42%",mobilePosition:"center 35%"},
  "1063": {src:"/pets/pet-1063.webp",alt:"Vigilant Oculazen in desert sundial plaza with long geometric shadows and amber dust at sunset",position:"center 42%",mobilePosition:"center 35%"},
  "1064": {src:"/pets/pet-1064.webp",alt:"Oculazen in quiet arcane library with tall curved shelves, teal lamps and drifting blank parchment",position:"center 42%",mobilePosition:"center 35%"},
  "1065": {src:"/pets/pet-1065.webp",alt:"Biruta in canopy rope village with red woven textiles and suspended seed storage baskets, green daylight",position:"center 42%",mobilePosition:"center 35%"},
  "1067": {src:"/pets/pet-1067.webp",alt:"Scorpion in blue sand dunes around a fossilized spiral shell under crisp rose dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1068": {src:"/pets/pet-1068.webp",alt:"Krao Test Subject in ruined containment chamber with shattered stone rings and crimson magical residue",position:"center 42%",mobilePosition:"center 35%"},
  "1069": {src:"/pets/pet-1069.webp",alt:"Stone Spirit in narrow glacial crevasse lit from overhead, angular frost crystals and powder snow",position:"center 42%",mobilePosition:"center 35%"},
  "1071": {src:"/pets/pet-1071.webp",alt:"Cadaver Insectoid in ancient catacomb garden with black roots, scarlet fungi and green moss, no gore or bodies",position:"center 42%",mobilePosition:"center 35%"},
  "1046": {src:"/pets/pet-1046.webp",alt:"Armadon in dusty ochre savanna under an enormous baobab with scattered seed pods",position:"center 42%",mobilePosition:"center 35%"},
  "1047": {src:"/pets/pet-1047.webp",alt:"Aberrant Armadon in icy cobblestone fjord shore under steel fog with stranded ship timbers",position:"center 42%",mobilePosition:"center 35%"},
  "1048": {src:"/pets/pet-1048.webp",alt:"Forest Spirit in ancient hollow oak interior lined with acorns and soft green reflected daylight",position:"center 42%",mobilePosition:"center 35%"},
  "1049": {src:"/pets/pet-1049.webp",alt:"Mutated Forest Spirit in petrified forest with white branching trunks and saffron dust, dim violet horizon",position:"center 42%",mobilePosition:"center 35%"},
  "1050": {src:"/pets/pet-1050.webp",alt:"Gravi in rose quartz garden with delicate pink flowering shrubs and alabaster stepping stones",position:"center 42%",mobilePosition:"center 35%"},
  "1051": {src:"/pets/pet-1051.webp",alt:"Magic Gravi in moonflower conservatory with fogged curved glass, silver-blue lanterns and hanging plants",position:"center 42%",mobilePosition:"center 35%"},
  "1052": {src:"/pets/pet-1052.webp",alt:"Large Leaf Gravi in sun-dappled tropical cenote edge with broad banana leaves and limestone arches",position:"center 42%",mobilePosition:"center 35%"},
  "1053": {src:"/pets/pet-1053.webp",alt:"Aberrant Potcrab in black pebble shore beside a wrecked red rowboat, pale overcast waves",position:"center 42%",mobilePosition:"center 35%"},
  "1054": {src:"/pets/pet-1054.webp",alt:"Mumu Warrior in hillside palisade training yard with straw dummies and wooden shields, copper evening",position:"center 42%",mobilePosition:"center 35%"},
  "1055": {src:"/pets/pet-1055.webp",alt:"Grave Rat in forgotten mausoleum stairs, fallen bronze urns and soft lavender mist, no corpses",position:"center 42%",mobilePosition:"center 35%"},
  "1056": {src:"/pets/pet-1056.webp",alt:"Drakan Probe in abandoned magical laboratory with rotating brass rings, violet conduits and broken glass columns",position:"center 42%",mobilePosition:"center 35%"},
  "1057": {src:"/pets/pet-1057.webp",alt:"Coradon in bioluminescent sea cave beside dark still water, blue ripples and hanging limestone curtains",position:"center 42%",mobilePosition:"center 35%"},
  "1034": {src:"/pets/pet-1034.webp",alt:"Giant Sparkie in amethyst cavern with golden honeycomb mineral formations and tiny waterfalls",position:"center 42%",mobilePosition:"center 35%"},
  "1035": {src:"/pets/pet-1035.webp",alt:"Skama in geothermal pool blue water under billowing steam with orange mineral terraces",position:"center 42%",mobilePosition:"center 35%"},
  "1036": {src:"/pets/pet-1036.webp",alt:"Lupyllini in wheat terraces around a windmill on a ridge, late summer wind, warm creamy light",position:"center 42%",mobilePosition:"center 35%"},
  "1037": {src:"/pets/pet-1037.webp",alt:"Male Crestlich in avocado grove on black volcanic soil, woven hanging seed baskets, filtered afternoon sun",position:"center 42%",mobilePosition:"center 35%"},
  "1038": {src:"/pets/pet-1038.webp",alt:"Airon in wind-sculpted beach dunes with bleached driftwood and blue sea oats at dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1039": {src:"/pets/pet-1039.webp",alt:"Crestlich in rainforest waterfall ledge with bright red heliconia leaves and misty rainbow",position:"center 42%",mobilePosition:"center 35%"},
  "1040": {src:"/pets/pet-1040.webp",alt:"Aullaeu Shaman in celestial observatory with bronze astrolabes and blue mosaic floor under a starry sky",position:"center 42%",mobilePosition:"center 35%"},
  "1041": {src:"/pets/pet-1041.webp",alt:"Cave Bat in limestone stalactite cavern with amber shafts from a small skylight, hanging upside down then wings half spread",position:"center 42%",mobilePosition:"center 35%"},
  "1042": {src:"/pets/pet-1042.webp",alt:"Ursus in salmon stream under redwood trunks and morning fog, shallow rushing water over smooth stones",position:"center 42%",mobilePosition:"center 35%"},
  "1043": {src:"/pets/pet-1043.webp",alt:"Elite Ursus in rust-red badlands with sparse teal succulent plants, dramatic dark storm overhead",position:"center 42%",mobilePosition:"center 35%"},
  "1044": {src:"/pets/pet-1044.webp",alt:"Aultross's Doppelganger in windy lighthouse balcony of pale stone overlooking rough gray sea, torn sailcloth, breaking dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1045": {src:"/pets/pet-1045.webp",alt:"Sylphen in giant water-lily pond at blue hour, floating pale blossoms and luminous reflections",position:"center 42%",mobilePosition:"center 35%"},
  "1018": {src:"/pets/pet-1018.webp",alt:"Varg Berserker in abandoned mountain foundry, cold blue dawn, enormous silent forge and scattered iron gears",position:"center 42%",mobilePosition:"center 35%"},
  "1021": {src:"/pets/pet-1021.webp",alt:"Aberrant Odyle Spider in crimson bramble thicket under silver fog, dew-covered thorns and dark red berries",position:"center 42%",mobilePosition:"center 35%"},
  "1022": {src:"/pets/pet-1022.webp",alt:"Crasaur in coral lagoon shallows, soft tropical pink morning, underwater caustics on pale sand",position:"center 42%",mobilePosition:"center 35%"},
  "1025": {src:"/pets/pet-1025.webp",alt:"Mutated Aberrant Odyle Spider in sulfur terraces with yellow mineral pools, white steam and ochre stones, hard midday sun",position:"center 42%",mobilePosition:"center 35%"},
  "1026": {src:"/pets/pet-1026.webp",alt:"Krall Warrior in windy mountain pass checkpoint, blue pennants, carved stone milestones, approaching thunderstorm",position:"center 42%",mobilePosition:"center 35%"},
  "1027": {src:"/pets/pet-1027.webp",alt:"Withered Agrint in dry riverbed with bleached driftwood, scattered amber leaves and silver evening light",position:"center 42%",mobilePosition:"center 35%"},
  "1028": {src:"/pets/pet-1028.webp",alt:"Krao Mutant in fractured crimson geode interior, sloping mineral plates, low glowing fissures",position:"center 42%",mobilePosition:"center 35%"},
  "1029": {src:"/pets/pet-1029.webp",alt:"Klaw Scout in overgrown aqueduct rooftop in morning mist, broken arches and a narrow stream high above jungle",position:"center 42%",mobilePosition:"center 35%"},
  "1030": {src:"/pets/pet-1030.webp",alt:"Nagarant Guardian Warrior in sunken marble hall with ankle-deep water, turquoise tile mosaics and shafts of sunlight",position:"center 42%",mobilePosition:"center 35%"},
  "1031": {src:"/pets/pet-1031.webp",alt:"Konutin Worker in rustic watermill among yellow gourds and stacked logs, golden afternoon",position:"center 42%",mobilePosition:"center 35%"},
  "1032": {src:"/pets/pet-1032.webp",alt:"Elite Keneire in starlit heather moor with a lonely standing stone circle, purple ground cover, no moon",position:"center 42%",mobilePosition:"center 35%"},
  "1033": {src:"/pets/pet-1033.webp",alt:"Elite Manduri Fighter in terraced red-clay canyon with massive sculpted guardian heads, late dusk and torch niches",position:"center 42%",mobilePosition:"center 35%"},
  "1006": {src:"/pets/sparkie-emerald.webp",alt:"Sparkie on a rain-soaked jungle canopy branch",position:"center 42%",mobilePosition:"35% 35%"},
  "1007": {src:"/pets/potcrab-tidepool.webp",alt:"Potcrab in a sunlit coastal tide pool",position:"center 42%",mobilePosition:"center 35%"},
  "1008": {src:"/pets/baby-spider-fern.webp",alt:"Baby Odyle Spider on a dew-covered fern web",position:"center 42%",mobilePosition:"center 35%"},
  "1009": {src:"/pets/kernon-ice-lake.webp",alt:"Kernon on a frozen lake at pink dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1010": {src:"/pets/manduri-arena.webp",alt:"Manduri Fighter in a ruined jungle arena",position:"center 42%",mobilePosition:"center 35%"},
  "1011": {src:"/pets/skyray-cloud-canyon.webp",alt:"Skyray above a cloud-filled sandstone canyon",position:"center 42%",mobilePosition:"center 35%"},
  "1012": {src:"/pets/fungie-orchard.webp",alt:"Fungie in an apple orchard in the rain",position:"center 42%",mobilePosition:"center 35%"},
  "1013": {src:"/pets/swarm-meteor.webp",alt:"Swarm inside a star-lit meteor crater",position:"center 42%",mobilePosition:"35% 35%"},
  "1014": {src:"/pets/guard-dog-fortress.webp",alt:"Drakan Guard Dog outside an iron fortress in the rain",position:"center 42%",mobilePosition:"35% 35%"},
  "1015": {src:"/pets/kailin-coast.webp",alt:"Kailin on a white chalk coastal cliff",position:"center 42%",mobilePosition:"35% 35%"},
  "1016": {src:"/pets/slink-reeds.webp",alt:"Slink in a papyrus river delta at sunset",position:"center 42%",mobilePosition:"35% 35%"},
  "1017": {src:"/pets/warshaman-camp.webp",alt:"Krall Warshaman in an ashen ritual camp",position:"center 42%",mobilePosition:"center 35%"},
  "1111": {src:"/pets/swift-lugi-autumn.webp",alt:"Swift Lugi crossing a golden autumn birch valley",position:"center 42%",mobilePosition:"40% 35%"},
  "1112": {src:"/pets/merchant-lugi-oasis.webp",alt:"Wandering Merchant Lugi resting in a sunlit desert caravan courtyard",position:"center 42%",mobilePosition:"center 35%"},
  "1245": {src:"/pets/kumiho-blue-flame.webp",alt:"Azure Flame Kumiho beside blue spirit flames in a tidal shrine",position:"center 42%",mobilePosition:"30% 35%"},
  "1002": {src:"/pets/krall-quarry.webp",alt:"Krall Laborer standing in a red-rock quarry",position:"center 42%",mobilePosition:"center 35%"},
  "1003": {src:"/pets/specter-root-temple.webp",alt:"Forest Specter hovering in a flooded cathedral of tree roots",position:"center 42%",mobilePosition:"center 35%"},
  "1005": {src:"/pets/klaw-salt-flats.webp",alt:"Klaw on reflective salt flats beneath purple crystal spires",position:"center 42%",mobilePosition:"center 35%"},
  "1113": {src:"/pets/white-dragon-glacier.webp",alt:"White Dragon standing on an alpine glacier beneath snowy mountain peaks",position:"center 42%",mobilePosition:"center 35%"},
  "1204": {src:"/pets/pagati-bamboo.webp",alt:"Pagati in a rain-soaked bamboo forest beside a vermilion footbridge",position:"center 42%",mobilePosition:"center 35%"},
  "1066": {src:"/pets/papis-mushroom-grove.webp",alt:"Papis hovering among glowing amber mushrooms on the forest floor",position:"center 42%",mobilePosition:"center 35%"},
  "1004": {src:"/pets/fossa-sanctuary-refined.png",alt:"Fossa in the moonlit floating-island sanctuary",position:"center 42%"},
  "1240": {src:"/pets/white-bunny-meadow.webp",alt:"White Bunny in a sunny spring meadow beside a tree-root burrow",position:"center 42%"},
  "1211": {src:"/pets/sky-whale-aurora.webp",alt:"Sky Whale flying beneath green auroras above distant storm clouds",position:"center 42%",mobilePosition:"35% 35%"},
  "1001": {src:"/pets/black-dragon-cavern.webp",alt:"Black Dragon guarding a basalt cavern illuminated by molten lava",position:"center 42%",mobilePosition:"28% 35%"},
};
export default petScenes;
