// Individual sanctuary illustrations; pets without a scene retain their reference portrait.
const petScenes = {
  "1034": {src:"/pets/pet-1034.webp",alt:"Giant Sparkie in amethyst cavern with golden honeycomb mineral formations and tiny waterfalls",position:"center 42%",mobilePosition:"center 35%"},
  "1035": {src:"/pets/pet-1035.webp",alt:"Skama in geothermal pool blue water under billowing steam with orange mineral terraces",position:"center 42%",mobilePosition:"center 35%"},
  "1036": {src:"/pets/pet-1036.webp",alt:"Lupyllini in wheat terraces around a windmill on a ridge, late summer wind, warm creamy light",position:"center 42%",mobilePosition:"center 35%"},
  "1037": {src:"/pets/pet-1037.webp",alt:"Male Crestlich in avocado grove on black volcanic soil, woven hanging seed baskets, filtered afternoon sun",position:"center 42%",mobilePosition:"center 35%"},
  "1038": {src:"/pets/pet-1038.webp",alt:"Airon in wind-sculpted beach dunes with bleached driftwood and blue sea oats at dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1039": {src:"/pets/pet-1039.webp",alt:"Crestlich in rainforest waterfall ledge with bright red heliconia leaves and misty rainbow",position:"center 42%",mobilePosition:"center 35%"},
  "1040": {src:"/pets/pet-1040.webp",alt:"Aullaeu Shaman in celestial observatory with bronze astrolabes and blue mosaic floor under a starry sky",position:"center 42%",mobilePosition:"center 35%"},
  "1041": {src:"/pets/pet-1041.webp",alt:"Cave Bat in limestone stalactite cavern with amber shafts from a small skylight, hanging upside down then wings half spread",position:"center 42%",mobilePosition:"center 35%"},
  "1042": {src:"/pets/pet-1042.webp",alt:"Ursus in salmon stream under redwood trunks and morning fog, shallow rushing water over smooth stones",position:"center 42%",mobilePosition:"center 35%"},
  "1043": {src:"/pets/pet-1043.webp",alt:"Elite Ursus in rust-red badlands with sparse teal succulent plants, dramatic dark storm overhead",position:"center 42%",mobilePosition:"center 35%"},
  "1044": {src:"/pets/pet-1044.webp",alt:"Aultross's Doppelganger in windy lighthouse balcony of pale stone overlooking rough gray sea, torn sailcloth, breaking dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1045": {src:"/pets/pet-1045.webp",alt:"Sylphen in giant water-lily pond at blue hour, floating pale blossoms and luminous reflections",position:"center 42%",mobilePosition:"center 35%"},
  "1018": {src:"/pets/pet-1018.webp",alt:"Varg Berserker in abandoned mountain foundry, cold blue dawn, enormous silent forge and scattered iron gears",position:"center 42%",mobilePosition:"center 35%"},
  "1021": {src:"/pets/pet-1021.webp",alt:"Aberrant Odyle Spider in crimson bramble thicket under silver fog, dew-covered thorns and dark red berries",position:"center 42%",mobilePosition:"center 35%"},
  "1022": {src:"/pets/pet-1022.webp",alt:"Crasaur in coral lagoon shallows, soft tropical pink morning, underwater caustics on pale sand",position:"center 42%",mobilePosition:"center 35%"},
  "1025": {src:"/pets/pet-1025.webp",alt:"Mutated Aberrant Odyle Spider in sulfur terraces with yellow mineral pools, white steam and ochre stones, hard midday sun",position:"center 42%",mobilePosition:"center 35%"},
  "1026": {src:"/pets/pet-1026.webp",alt:"Krall Warrior in windy mountain pass checkpoint, blue pennants, carved stone milestones, approaching thunderstorm",position:"center 42%",mobilePosition:"center 35%"},
  "1027": {src:"/pets/pet-1027.webp",alt:"Withered Agrint in dry riverbed with bleached driftwood, scattered amber leaves and silver evening light",position:"center 42%",mobilePosition:"center 35%"},
  "1028": {src:"/pets/pet-1028.webp",alt:"Krao Mutant in fractured crimson geode interior, sloping mineral plates, low glowing fissures",position:"center 42%",mobilePosition:"center 35%"},
  "1029": {src:"/pets/pet-1029.webp",alt:"Klaw Scout in overgrown aqueduct rooftop in morning mist, broken arches and a narrow stream high above jungle",position:"center 42%",mobilePosition:"center 35%"},
  "1030": {src:"/pets/pet-1030.webp",alt:"Nagarant Guardian Warrior in sunken marble hall with ankle-deep water, turquoise tile mosaics and shafts of sunlight",position:"center 42%",mobilePosition:"center 35%"},
  "1031": {src:"/pets/pet-1031.webp",alt:"Konutin Worker in rustic watermill among yellow gourds and stacked logs, golden afternoon",position:"center 42%",mobilePosition:"center 35%"},
  "1032": {src:"/pets/pet-1032.webp",alt:"Elite Keneire in starlit heather moor with a lonely standing stone circle, purple ground cover, no moon",position:"center 42%",mobilePosition:"center 35%"},
  "1033": {src:"/pets/pet-1033.webp",alt:"Elite Manduri Fighter in terraced red-clay canyon with massive sculpted guardian heads, late dusk and torch niches",position:"center 42%",mobilePosition:"center 35%"},
  "1006": {src:"/pets/sparkie-emerald.webp",alt:"Sparkie on a rain-soaked jungle canopy branch",position:"center 42%",mobilePosition:"35% 35%"},
  "1007": {src:"/pets/potcrab-tidepool.webp",alt:"Potcrab in a sunlit coastal tide pool",position:"center 42%",mobilePosition:"center 35%"},
  "1008": {src:"/pets/baby-spider-fern.webp",alt:"Baby Odyle Spider on a dew-covered fern web",position:"center 42%",mobilePosition:"center 35%"},
  "1009": {src:"/pets/kernon-ice-lake.webp",alt:"Kernon on a frozen lake at pink dawn",position:"center 42%",mobilePosition:"center 35%"},
  "1010": {src:"/pets/manduri-arena.webp",alt:"Manduri Fighter in a ruined jungle arena",position:"center 42%",mobilePosition:"center 35%"},
  "1011": {src:"/pets/skyray-cloud-canyon.webp",alt:"Skyray above a cloud-filled sandstone canyon",position:"center 42%",mobilePosition:"center 35%"},
  "1012": {src:"/pets/fungie-orchard.webp",alt:"Fungie in an apple orchard in the rain",position:"center 42%",mobilePosition:"center 35%"},
  "1013": {src:"/pets/swarm-meteor.webp",alt:"Swarm inside a star-lit meteor crater",position:"center 42%",mobilePosition:"35% 35%"},
  "1014": {src:"/pets/guard-dog-fortress.webp",alt:"Drakan Guard Dog outside an iron fortress in the rain",position:"center 42%",mobilePosition:"35% 35%"},
  "1015": {src:"/pets/kailin-coast.webp",alt:"Kailin on a white chalk coastal cliff",position:"center 42%",mobilePosition:"35% 35%"},
  "1016": {src:"/pets/slink-reeds.webp",alt:"Slink in a papyrus river delta at sunset",position:"center 42%",mobilePosition:"35% 35%"},
  "1017": {src:"/pets/warshaman-camp.webp",alt:"Krall Warshaman in an ashen ritual camp",position:"center 42%",mobilePosition:"center 35%"},
  "1111": {src:"/pets/swift-lugi-autumn.webp",alt:"Swift Lugi crossing a golden autumn birch valley",position:"center 42%",mobilePosition:"40% 35%"},
  "1112": {src:"/pets/merchant-lugi-oasis.webp",alt:"Wandering Merchant Lugi resting in a sunlit desert caravan courtyard",position:"center 42%",mobilePosition:"center 35%"},
  "1245": {src:"/pets/kumiho-blue-flame.webp",alt:"Azure Flame Kumiho beside blue spirit flames in a tidal shrine",position:"center 42%",mobilePosition:"30% 35%"},
  "1002": {src:"/pets/krall-quarry.webp",alt:"Krall Laborer standing in a red-rock quarry",position:"center 42%",mobilePosition:"center 35%"},
  "1003": {src:"/pets/specter-root-temple.webp",alt:"Forest Specter hovering in a flooded cathedral of tree roots",position:"center 42%",mobilePosition:"center 35%"},
  "1005": {src:"/pets/klaw-salt-flats.webp",alt:"Klaw on reflective salt flats beneath purple crystal spires",position:"center 42%",mobilePosition:"center 35%"},
  "1113": {src:"/pets/white-dragon-glacier.webp",alt:"White Dragon standing on an alpine glacier beneath snowy mountain peaks",position:"center 42%",mobilePosition:"center 35%"},
  "1204": {src:"/pets/pagati-bamboo.webp",alt:"Pagati in a rain-soaked bamboo forest beside a vermilion footbridge",position:"center 42%",mobilePosition:"center 35%"},
  "1066": {src:"/pets/papis-mushroom-grove.webp",alt:"Papis hovering among glowing amber mushrooms on the forest floor",position:"center 42%",mobilePosition:"center 35%"},
  "1004": {src:"/pets/fossa-sanctuary-refined.png",alt:"Fossa in the moonlit floating-island sanctuary",position:"center 42%"},
  "1240": {src:"/pets/white-bunny-meadow.webp",alt:"White Bunny in a sunny spring meadow beside a tree-root burrow",position:"center 42%"},
  "1211": {src:"/pets/sky-whale-aurora.webp",alt:"Sky Whale flying beneath green auroras above distant storm clouds",position:"center 42%",mobilePosition:"35% 35%"},
  "1001": {src:"/pets/black-dragon-cavern.webp",alt:"Black Dragon guarding a basalt cavern illuminated by molten lava",position:"center 42%",mobilePosition:"28% 35%"},
};
export default petScenes;
