export const emblemBase = "https://assets.playnccdn.com/res/aion2/update/2026/global/260421_teaser/4th/pc/img/sec6";

export const classList = [
  {name:"Templar",slug:"templar",emblem:"a803b8ff93e66eb3f53d072afefbfab8973db1ae"},
  {name:"Gladiator",slug:"gladiator",emblem:"9f148fff4326b424e31e6a302c53f9f0a3bc20e2"},
  {name:"Assassin",slug:"assassin",emblem:"60b63119fe4abbc95da8536381693cf5d27e9bff"},
  {name:"Ranger",slug:"ranger",emblem:"5135150c4edcbfd46fa724345ba0426243ba7612"},
  {name:"Sorcerer",slug:"sorcerer",emblem:"f23f42707808d521e1fa9a54ebbff2df2a5f4a19"},
  {name:"Spiritmaster",slug:"spiritmaster",emblem:"d34fd5fab057473228b11c9d21093420fd2243ea"},
  {name:"Cleric",slug:"cleric",emblem:"d6e8b2e7f1e0c92f2e2eccc27aa3c7114a428b17"},
  {name:"Chanter",slug:"chanter",emblem:"6aa4fcc86358be7383100c19ef0bbcd653339441"},
];

export const classData = {
  templar:{role:"Tanque",weapon:"Espada larga",summary:"El Templar protege al grupo desde el frente: atrae la atención de los enemigos, aguanta el daño y crea espacio para que sus aliados puedan atacar con seguridad.",playstyle:"Mantén la amenaza con golpes y provocaciones; reserva tus defensas para los ataques fuertes del enemigo. Premia el buen tiempo y el control de la pelea.",active:["Vicious Strike","Pummel","Poach","Shield Smite","Judgment","Flash Rampage","Debilitating Smash","Warding Strike","Shield Rush","Annihilate","Punishment","Defiance","Dodge","Empyrean Lord’s Punishment","Nezekan’s Shield","Shield of Protection","Taunt","Armor of Balance","Second Skin","Doom Shield","Noble Armor","Comrade in Arms","Grapple","Assault Fury","Battlefield Banner"],passive:["Enhance Health","Warding Shield","Punishing Benediction","Ironclad Defense","Guarding Seal","Impact Hit","Insulting Roar","Fury","Survival Willpower","Block Pain"]},
  gladiator:{role:"Tanque / DPS",weapon:"Espadón",summary:"El Gladiator es un luchador de primera línea que usa un espadón para golpear a varios enemigos y mantenerse en combate mientras inflige daño.",playstyle:"Acércate al grupo enemigo, encadena ataques amplios y usa tus herramientas defensivas y de recuperación para resistir. Puede alternar entre daño y apoyo como tanque secundario.",active:["Keen Strike","Rending Blow","Leaping Slam","Mocking Blade","Overhead Slam","Sword Aura Rampage","Ankle Slice","Crushing Wave","Rush Strike","Aerial Snare","Ruinous Blow","Defiance","Dodge","Wrath Wave","Lunge Stance","Zikel’s Blessing","Focused Block","Armor of Balance","Blade Toss","Tenaciousness","Lifestealing Blade","Rage Burst","Wave Armor","Forced Restraint","Assault Strike","Fracturing Rush"],passive:["Survival Stance","Protection Armor","Blood Absorption","Identify Weakness","Attack Preparation","Impact Hit","Destructive Impulse","Experienced Counterstrike","Survival Willpower","Murderous Burst"]},
  assassin:{role:"DPS",weapon:"Dagas",summary:"El Assassin busca el momento oportuno para aparecer desde las sombras y concentrar una ráfaga de golpes sobre un objetivo vulnerable.",playstyle:"Entra desde sigilo, aprovecha los ataques por la espalda y reposiciónate antes de quedar atrapado. Depende de la precisión, la movilidad y el momento de entrada.",active:["Quick Slice","Savage Roar","Shadowstrike","Ambush","Heart Gore","Storm Rampage","Whirlwind Slice","Flash Slice","Infiltrate","Shadow Fall","Insignia Explosion","Defiance","Dodge","Savage Fang","Swift Contract","Smoke Bomb","Evasion Stance","Spiral Slice","Shadow Walk","Throw Shadowblade","Triniel’s Dagger","Aerial Bind","Illusive Clone","Evasion Contract","Assault Ambush","Shadowstep"],passive:["Heightened Sixth Sense","Exploit Weakness","Apply Poison","Rear Smite","Assault Stance","Impact Hit","Ambush Stance","Defense Break","Revitalization Contract","Determination"]},
  ranger:{role:"DPS",weapon:"Arco",summary:"El Ranger combate a larga distancia con ataques precisos y potentes, y usa su movilidad para conservar la ventaja de alcance.",playstyle:"Abre desde lejos con disparos de alto impacto y mantén presión con una secuencia de flechas. El posicionamiento y el control de distancia son clave para sobrevivir.",active:["Snipe","Tempest Shot","Snare Shot","Marking Shot","Drill Dart","Arrow Scattershot","Gale Arrow","Explosion Trap","Burst Arrow","Suppressing Arrow","Deadshot","Defiance","Dodge","Arrow Storm","Vaizel’s Authority","Bow of Blessing","Ambush Kick","Ensnaring Trap","Illusory Arrow","Stealth","Sealing Arrow","Mother Nature’s Breath","Griffon Arrow","Explosive Arrow","Assault Smite","Supporting Fire"],passive:["Vigilant Eye","Concentrated Fire","Wind Vigor","Focused Eye","Hunter’s Resolve","Unyielding Resolve","Rooting Eye","Melee Fire","Revitalization Contract","Hunter’s Soul"]},
  sorcerer:{role:"DPS",weapon:"Libro de hechizos",summary:"El Sorcerer domina el combate a distancia con magia de fuego y hielo: combina daño explosivo con efectos que frenan y controlan a sus objetivos.",playstyle:"Alterna fuego para ejercer presión y hielo para ralentizar o inmovilizar. Su gran daño requiere mantener la distancia y elegir bien cuándo lanzar cada habilidad.",active:["Flame Arrow","Ice Chain","Firestorm","Bittercold Wind","Blaze","Flame Scattershot","Frost","Winter’s Shackles","Frost Burst","Wish of Concentration","Hellfire","Defiance","Dodge","Divine Burst","Steel Barrier","Element Enhancement","Curse: Tree","Arctic Armor","Soul Freeze","Cold Storm","Fire Wall","Lumiel’s Space","Delayed Explosion","Glacial Smite","Assault Bombardment","Hibernation"],passive:["Fire Mark","Robe of Earth","Cold Snap","Robe of Flame","Absorb Essence","Grace of Resistance","Robe of Cold","Grace of Enhancement","Revitalization Contract","Vitality Evaporation"]},
  spiritmaster:{role:"DPS",weapon:"Orbe",summary:"El Spiritmaster invoca espíritus elementales que atacan junto a él mientras desgasta a sus enemigos con daño, debilitamientos y control.",playstyle:"Mantén activos tus espíritus y combina sus ataques con efectos elementales y habilidades de control. La gestión constante de las invocaciones marca el ritmo de la clase.",active:["Cold Shock","Combustion","Summon: Fire Spirit","Summon: Water Spirit","Jointstrike: Curse","Rapid Scattershot","Summon: Earth Spirit","Dimensional Control","Summon: Wind Spirit","Soul’s Cry","Elemental Fusion","Defiance","Dodge","Jointstrike: Destructive Attack","Flame Blessing","Summon: Ancient Spirit","Jointstrike: Corrode","Kaisinel’s Power","Siphon","Cry of Terror","Cursed Cloud","Seize Magic","Magic Block","Assault Terror","Command: Proxy"],passive:["Spirit Strike","Spirit Protection","Spirit’s Descent","Corrode","Spirit Revitalization","Mental Focus","Consecutive Countercurrent","Spirit Communion","Revitalization Contract","Element Unification"]},
  cleric:{role:"Sanador",weapon:"Maza",summary:"El Cleric mantiene con vida al grupo con curaciones y protecciones, y puede resucitar aliados caídos. También aporta daño a distancia cuando la situación lo permite.",playstyle:"Observa la salud del grupo, alterna curaciones directas y sostenidas con escudos y mantente en una posición segura. Añade ataques entre curaciones cuando el equipo esté estable.",active:["Earth’s Retribution","Judgment Thunder","Debilitating Mark","Divine Aura","Chain of Torment","Lightning Strike Scattershot","Light of Regeneration","Condemnation","Healing Light","Radiant Recovery","Bolt","Defiance","Dodge","Power Burst","Absolution","Benevolence","Prayer of Amplification","Summon Resurrection","Earth Punishment","Salvation","Root","Light of Protection","Yustiel’s Power","Voice of Doom","Assault Mark","Noble Aura"],passive:["Warm Benediction","Empyrean Lords’ Benediction","Empyrean Lord’s Grace","Healing Enhancement","Immortal Veil","Heal Block","Prayer of Concentration","Earth’s Grace","Survival Willpower","Radiant Benediction"]},
  chanter:{role:"Sanador / DPS",weapon:"Bastón",summary:"El Chanter combina apoyo y combate cercano: fortalece a su equipo con mantras, aporta curación y lucha con su bastón.",playstyle:"Mantén los beneficios del grupo mientras enlazas golpes y curaciones según lo que pida la pelea. Aporta resistencia y daño sostenido como apoyo híbrido.",active:["Onslaught","Incandescent Blow","Rushing Smash","Impactful Crush","Dark Crush","Gust Rampage","Heat Wave Blow","Recuperation","Tremor Crush","Wave Blow","Spinning Strike","Defiance","Dodge","Obliterate","Undefeated Mantra","Focused Defense","Sprint Mantra","Fracturing Blow","Marchutan’s Wrath","Impeding Authority","Ensnaring Mark","Healing Touch","Power of the Storm","Guardian Blessing","Assault Shock","Barrier Spell"],passive:["Blessing of Life","Crossguard","Protection Circle","Inspiring Spell","Attack Preparation","Impact Hit","Raging Spell","Earth’s Promise","Survival Willpower","Wind’s Promise"]},
};
